import {
  DISCOVERED_LIFECYCLE_STEP_SELECTION_SOURCES,
  DISCOVER_PROJECT_SELECTION_SOURCES,
  DOCTOR_SELECTION_SOURCES,
  GUIDE_ENTRYPOINT_SELECTION_SOURCES,
  GUIDE_LIFECYCLE_STEP_SELECTION_SOURCES,
  GUIDE_SELECTION_SOURCES,
  HANDOFF_SELECTION_SOURCES,
  LIFECYCLE_ACTION_SELECTION_SOURCES,
  LIFECYCLE_NEXT_SELECTION_SOURCES
} from "./core/agent-lifecycle.js";
import { STORE_INIT_SELECTION_SOURCES } from "./core/config.js";
import { REBUILD_SELECTION_SOURCES } from "./core/derived.js";
export { createEngine } from "./core/engine.js";
import {
  BOOT_SELECTION_SOURCES,
  LINK_EVENT_SELECTION_SOURCES,
  LIST_RECENT_SELECTION_SOURCES,
  MUTATION_EVENT_SELECTION_SOURCES,
  PROJECT_LIST_NEXT_ACTION_SELECTION_SOURCES,
  PROJECT_LIST_SELECTION_SOURCES,
  RECALL_SELECTION_SOURCES,
  REFRESH_CHANGE_NEXT_ACTION_SELECTION_SOURCES,
  REFRESH_SELECTION_SOURCES,
  SENSITIVE_REVISE_SELECTION_SOURCES,
  WRITE_SELECTION_SOURCES
} from "./core/engine.js";
import { NEXT_ACTION_SELECTION_SOURCES } from "./core/errors.js";
export {
  OPERATION_CONTRACTS,
  OPERATION_CONTRACTS_SELECTION_SOURCES,
  getOperationContract,
  getOperationContractByCliCommand,
  getOperationContractByMcpTool,
  getOperationContractIndex,
  getOperationContracts
} from "./operation-contracts.js";
import { PROJECT_INIT_SELECTION_SOURCES } from "./core/project.js";
export { parseRecord } from "./core/schema.js";
import { SYNC_RESULT_SELECTION_SOURCES, SYNC_STATUS_SELECTION_SOURCES } from "./sync/git.js";
export type { MorynRecord } from "./core/types.js";

export const version = "0.1.0";

export {
  DISCOVERED_LIFECYCLE_STEP_SELECTION_SOURCES,
  DISCOVER_PROJECT_SELECTION_SOURCES,
  DOCTOR_SELECTION_SOURCES,
  GUIDE_ENTRYPOINT_SELECTION_SOURCES,
  GUIDE_LIFECYCLE_STEP_SELECTION_SOURCES,
  GUIDE_SELECTION_SOURCES,
  HANDOFF_SELECTION_SOURCES,
  LIFECYCLE_ACTION_SELECTION_SOURCES,
  LIFECYCLE_NEXT_SELECTION_SOURCES,
  STORE_INIT_SELECTION_SOURCES,
  REBUILD_SELECTION_SOURCES,
  BOOT_SELECTION_SOURCES,
  LINK_EVENT_SELECTION_SOURCES,
  LIST_RECENT_SELECTION_SOURCES,
  MUTATION_EVENT_SELECTION_SOURCES,
  PROJECT_LIST_NEXT_ACTION_SELECTION_SOURCES,
  PROJECT_LIST_SELECTION_SOURCES,
  RECALL_SELECTION_SOURCES,
  REFRESH_CHANGE_NEXT_ACTION_SELECTION_SOURCES,
  REFRESH_SELECTION_SOURCES,
  SENSITIVE_REVISE_SELECTION_SOURCES,
  WRITE_SELECTION_SOURCES,
  NEXT_ACTION_SELECTION_SOURCES,
  PROJECT_INIT_SELECTION_SOURCES,
  SYNC_RESULT_SELECTION_SOURCES,
  SYNC_STATUS_SELECTION_SOURCES
};

export const SELECTION_SOURCE_CONTRACTS = {
  setup: {
    store_init: STORE_INIT_SELECTION_SOURCES,
    project_init: PROJECT_INIT_SELECTION_SOURCES,
    rebuild: REBUILD_SELECTION_SOURCES
  },
  core: {
    write: WRITE_SELECTION_SOURCES,
    mutation_event: MUTATION_EVENT_SELECTION_SOURCES,
    link_event: LINK_EVENT_SELECTION_SOURCES,
    sensitive_revise: SENSITIVE_REVISE_SELECTION_SOURCES,
    recall: RECALL_SELECTION_SOURCES,
    boot: BOOT_SELECTION_SOURCES,
    refresh: REFRESH_SELECTION_SOURCES,
    refresh_change_next_action: REFRESH_CHANGE_NEXT_ACTION_SELECTION_SOURCES,
    list_recent: LIST_RECENT_SELECTION_SOURCES,
    project_list: PROJECT_LIST_SELECTION_SOURCES,
    project_list_next_action: PROJECT_LIST_NEXT_ACTION_SELECTION_SOURCES
  },
  sync: {
    status: SYNC_STATUS_SELECTION_SOURCES,
    result: SYNC_RESULT_SELECTION_SOURCES
  },
  lifecycle: {
    guide: GUIDE_SELECTION_SOURCES,
    guide_lifecycle_step: GUIDE_LIFECYCLE_STEP_SELECTION_SOURCES,
    guide_entrypoint: GUIDE_ENTRYPOINT_SELECTION_SOURCES,
    lifecycle_next: LIFECYCLE_NEXT_SELECTION_SOURCES,
    lifecycle_action: LIFECYCLE_ACTION_SELECTION_SOURCES,
    discover_project: DISCOVER_PROJECT_SELECTION_SOURCES,
    discovered_lifecycle_step: DISCOVERED_LIFECYCLE_STEP_SELECTION_SOURCES,
    handoff: HANDOFF_SELECTION_SOURCES,
    doctor: DOCTOR_SELECTION_SOURCES
  },
  recovery: {
    next_action: NEXT_ACTION_SELECTION_SOURCES
  }
} as const;

export const SELECTION_SOURCE_CONTRACTS_SELECTION_SOURCES = {
  contracts: "contracts",
  group: "contracts.<group>",
  contract: "contracts.<group>.<contract>",
  field: "contracts.<group>.<contract>.<field>"
} as const;

export function getSelectionSourceContracts() {
  return {
    contracts: SELECTION_SOURCE_CONTRACTS,
    selection_sources: SELECTION_SOURCE_CONTRACTS_SELECTION_SOURCES
  };
}
